---
services:
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx_static_server
    ports:
      - "8080:80"
    volumes:
      - ./static:/usr/share/nginx/html:ro
      - ./js/src:/usr/share/nginx/js:ro
    restart: unless-stopped
    command: >
      /bin/sh -c "echo 'server {
        listen 80;
        server_name localhost;
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
        location /js {
          alias /usr/share/nginx/js;
        }
      }' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  api:
    build:
      context: go 
      dockerfile: Dockerfile
      target: build
    image: api
    volumes:
    # Sometimes we want to do local dev with a `docker-compose up`. For that, we
    # need the develop.watch block defined below. But sometimes we need to run
    # unit tests with `docker-composer run`. For that, we need volume mounts,
    # not file watch/sync. You can't have both watch and volume mounts for the
    # same files at the same time. So DISABLE_VOLUME is a hack that let's us
    # disable volume mounts if we want to do `docker-compose up` (and let the
    # watch/sync takeover)
    - "${DISABLE_VOLUME:-./go:/app}"
    environment:
      - TOMEDOME_DB_FILEPATH=/app/internal/assets/mock_data.json
      - TOMEDOME_STRATZ_API_KEY=${TOMEDOME_STRATZ_API_KEY:-nokey}
      - LOGLEVEL=${LOGLEVEL:-debug}
      - LOCALDEV=true
      - GOTEST_PALETTE=${GOTEST_PALETTE:-red,green}
      - TOMEDOME_STRATZ_API_KEY=${TOMEDOME_STRATZ_API_KEY:-nokey}
    ports:
      - "8081:8080"
    command:
      - go
      - run
      - cmd/main.go
      - --backend
      - embedded
      - --run-server
    develop:
      watch:
        - action: sync+restart
          target: /app
          path: ./go